# Generated by Django 5.2 on 2025-12-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="text",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
