# Generated by Django 5.2.8 on 2025-12-22 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0002_post_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
    ]
